apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: netwatcher
  namespace: kube-system
spec:
  selector:
    matchLabels:
      danm.k8s.io: netwatcher
  template:
    metadata:
      labels:
        danm.k8s.io: netwatcher
    spec:
      serviceAccount: netwatcher
      hostNetwork: true
      dnsPolicy: ClusterFirst
      hostIPC: true
      hostPID: true
      initContainers:
        - name: install-danm
          image: danm-deployer:3.1.0
          imagePullPolicy: Always
          env:
          - name: SERVICEACCOUNTNAME
            value: "netwatcher"
          volumeMounts:
            - name: cni-bin
              mountPath: /target/cni-bin
            - name: netd
              mountPath: /target/netd
            - name: etckubernetes
              mountPath: /target/etc/kubernetes/
      containers:
        - name: netwatcher
          image: netwatcher:3.1.0
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
                - SYS_ADMIN
                - NET_ADMIN
                - NET_RAW
      tolerations:
       - effect: NoSchedule
         operator: Exists
       - effect: NoExecute
         operator: Exists
      terminationGracePeriodSeconds: 0
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt/cni/bin
        - name: netd
          hostPath:
            path: /etc/cni/net.d/
        - name: etckubernetes
          hostPath:
            path: /etc/kubernetes/
