---
apiVersion: danm.k8s.io/v1
kind: DanmNet
metadata:
  name: default
  namespace: kube-system
spec:
  NetworkID: default
  NetworkType: flannel
---
apiVersion: danm.k8s.io/v1
kind: DanmNet
metadata:
  name: flannel
  namespace: kube-system
spec:
  NetworkID: flannel
  NetworkType: flannel
---
apiVersion: danm.k8s.io/v1
kind: DanmNet
metadata:
  name: default
  namespace: default
spec:
  NetworkID: default
  NetworkType: flannel
